import type { Metadata } from 'next'
import { LegalPageLayout } from '@/components/legal/legal-page-layout'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms and conditions governing the use of Aether strategy builder and simulation platform.',
}

export default function TermsOfServicePage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="24 August 2026">
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you
        (&ldquo;User,&rdquo; &ldquo;you,&rdquo; or &ldquo;your&rdquo;) and Aether Systems Pvt. Ltd.
        (&ldquo;Aether,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;), governing your
        access to and use of the Aether web application, simulation engine, component library,
        marketplace, and related services (collectively, the &ldquo;Platform&rdquo;).
      </p>

      <p>
        By creating an account, accessing, or using the Platform, you acknowledge that you have read,
        understood, and agree to be bound by these Terms. If you do not agree, you must not access or
        use the Platform.
      </p>

      <h2>1. Nature of the Platform &amp; Not Investment Advice</h2>
      <p>
        Aether provides visual node-based software tools designed for formulating, backtesting,
        evaluating, and paper-trading algorithmic quantitative strategies. <strong>Aether is a technology provider, not a broker-dealer, registered investment advisor, portfolio manager, exchange, or financial institution.</strong>
      </p>
      <p>
        Nothing published on or generated by the Platform constitutes financial, tax, legal, or
        investment advice, nor does it constitute an offer or solicitation to buy or sell any security,
        derivative, digital asset, or financial instrument. You are solely responsible for all trading
        and investment decisions, whether simulated or conducted through third-party brokerages.
      </p>

      <h2>2. Account Eligibility &amp; Security</h2>
      <p>
        To access the Platform, you must be at least 18 years of age and legally capable of entering into
        a binding contract under applicable laws. You agree to provide accurate, current, and complete
        information during registration and to maintain the security of your login credentials.
      </p>
      <p>
        You are solely responsible for any activity that occurs under your account credentials. You must
        notify Aether immediately at <a href="mailto:security@aether.dev">security@aether.dev</a> if you
        suspect any unauthorized access or security compromise of your workspace or API keys.
      </p>

      <h2>3. Subscription Plans &amp; Simulation Credits</h2>
      <p>
        Aether operates on a hybrid model consisting of recurring subscriptions (Free, Starter, Pro)
        and pay-as-you-go simulation credits:
      </p>
      <ul>
        <li>
          <strong>Subscription Tiers:</strong> Subscriptions grant access to expanded bot limits, higher
          node capacities, advanced layer blocks (including Reinforcement Learning and Debate layers),
          extended historical backtest windows (up to 15 years on Pro), and multi-scenario backtesting
          capabilities.
        </li>
        <li>
          <strong>Simulation Credits:</strong> Credits purchased via pay-as-you-go bundles (100, 500, or
          1,000 credits) allow users on any plan to unlock specific component nodes permanently or run
          individual backtest simulations (typically 2 to 8 credits per run).
        </li>
        <li>
          <strong>Credit Expiration:</strong> Purchased simulation credits <strong>never expire</strong> and remain credited to your account balance indefinitely. Component unlocks purchased with credits remain unlocked permanently.
        </li>
        <li>
          <strong>Downgrades &amp; Limits:</strong> If you downgrade your subscription, existing bots and
          unlocked components are not deleted. Bots exceeding your new plan limits become read-only until
          you re-subscribe or archive bots to meet the tier threshold.
        </li>
      </ul>

      <h2>4. Marketplace &amp; Creator Program</h2>
      <p>
        The Aether Marketplace allows creators to share or monetize strategy presets, mini-presets, and
        custom subgraphs:
      </p>
      <ul>
        <li>
          <strong>Publishing:</strong> Free community presets may be published by eligible subscribed
          users. Selling paid presets requires an active Pro subscription tier.
        </li>
        <li>
          <strong>Creator Revenue Share:</strong> Pro creators receive an <strong>80% net revenue share</strong> on sales of their paid presets, subject to applicable platform processing fees, tax withholding, and minimum payout thresholds.
        </li>
        <li>
          <strong>Preset Licensing:</strong> When you publish a preset to the Marketplace, you grant other
          users a non-exclusive, worldwide license to clone, backtest, modify, and execute that preset
          within their personal Aether workspace. You warrant that your published presets do not infringe
          upon third-party intellectual property or violate confidentiality agreements.
        </li>
      </ul>

      <h2>5. Intellectual Property &amp; Strategy Ownership</h2>
      <p>
        <strong>Your Strategy IP:</strong> You retain full ownership and intellectual property rights in
        the proprietary trading logic, custom graph architectures, parameter tunings, and mathematical
        formulations that you construct within your private workspace. Aether does not claim ownership of
        your private bots or strategies.
      </p>
      <p>
        <strong>Platform IP:</strong> Aether Systems Pvt. Ltd. and its licensors retain all rights,
        title, and interest in the Platform, including the Loom graph editor canvas, visual node layouts,
        attribution calculation engines, simulation software, UI components, icons, and proprietary
        documentation.
      </p>

      <h2>6. Acceptable Use Policy</h2>
      <p>You agree not to engage in any of the following prohibited activities:</p>
      <ul>
        <li>Reverse engineering, decompiling, or attempting to extract the source code of the simulation engine or proprietary analytics layers.</li>
        <li>Reselling, redistributing, or sublicensing marketplace components or market data feeds outside the Platform.</li>
        <li>Using automated scrapers, bots, or scripts to overload, disrupt, or exploit the platform infrastructure.</li>
        <li>Deploying strategies designed to engage in market manipulation, spoofing, wash trading, or violating securities exchange rules.</li>
      </ul>

      <h2>7. Disclaimers of Warranty</h2>
      <p>
        THE PLATFORM, INCLUDING ALL DATA FEEDS, SIMULATION RUNS, AND BACKTEST ENGINES, IS PROVIDED ON AN
        &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER
        EXPRESS OR IMPLIED. AETHER EXPRESSLY DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
        PARTICULAR PURPOSE, ACCURACY OF MARKET DATA, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT
        SIMULATION RESULTS REFLECT REAL-WORLD EXECUTION CONDITIONS.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, IN NO EVENT SHALL AETHER SYSTEMS PVT. LTD.,
        ITS DIRECTORS, EMPLOYEES, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING TRADING LOSSES, CAPITAL LOSSES, LOST PROFITS, OR
        DATA LOSS, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE PLATFORM.
      </p>
      <p>
        OUR TOTAL AGGREGATE LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE TOTAL
        AMOUNT PAID BY YOU TO AETHER DURING THE TWELVE (12) MONTHS PRECEDING THE EVENT GIVING RISE TO
        LIABILITY.
      </p>

      <h2>9. Governing Law &amp; Jurisdiction</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the laws of the Republic of
        India, without regard to conflict of law principles. Any dispute, claim, or controversy arising
        out of or relating to these Terms or the Platform shall be subject to the exclusive jurisdiction
        of the competent courts situated in Mumbai, Maharashtra, India.
      </p>

      <h2>10. Modifications &amp; Inquiries</h2>
      <p>
        We may update these Terms from time to time. When changes are made, we will revise the &ldquo;Last
        updated&rdquo; date at the top of this page. Continued use of the Platform after changes take
        effect constitutes acceptance of the revised Terms.
      </p>
      <p>
        For any legal questions regarding these Terms, please contact us at{' '}
        <a href="mailto:legal@aether.dev">legal@aether.dev</a>.
      </p>
    </LegalPageLayout>
  )
}
